### ISSUE TITLE
Rendering problem with custom views

### ISSUE THREAD

**Issue by 3mph4515** [chrisbanes/philm#10]
With the last SDK update custom views render is broken:

The following classes could not be instantiated:
- app.philm.in.view.FontTextView (Open Class, Show Exception)
- app.philm.in.view.BackdropImageView (Open Class, Show Exception)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in 
the IDE  Exception Details java.lang.ClassCastException: 
com.android.layoutlib.bridge.android.BridgeContext cannot be cast to app.philm.in.PhilmApplication  at app.philm.in.PhilmApplication.from(PhilmApplication.java:39)   at app.philm.in.view.FontTextView.<init>(FontTextView.java:53)   at app.philm.in.view.FontTextView.<init>(FontTextView.java:47)   at java.lang.reflect.Constructor.newInstance(Constructor.java:408)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:755)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)   at android.view.LayoutInflater_Delegate.parseInclude(LayoutInflater_Delegate.java:116)   at android.view.LayoutInflater.parseInclude(LayoutInflater.java:782)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:745)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:727)   at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   at android.view.LayoutInflater.inflate(LayoutInflater.java:373)

How to fix it?

**Comment by 3mph4515** [comment]
Fixed with new right isInEditMode usage
